name: MSBuild

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  SOLUTION_FILE_PATH: SHOWOFF-NVSE/ShowOffNVSE.sln

permissions: write-all

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Build Debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}} /p:PostBuildEventUseInBuild=false

    - name: Generate Timestamp
      run: |
        timestamp=$(date +"%Y%m%d%H%M%S")
        echo "artifact_timestamp=$timestamp" >> $GITHUB_ENV
      shell: bash

    - name: Package Artifacts
      run: |
        $releaseDir = "SHOWOFF-NVSE\Release"
        $debugDir = "SHOWOFF-NVSE\Debug"
        New-Item -ItemType Directory -Name artifacts -Force | Out-Null
        New-Item -ItemType Directory -Name "nvse\plugins" -path $releaseDir -Force | Out-Null
        New-Item -ItemType Directory -Name "nvse\plugins" -path $debugDir -Force | Out-Null
        Copy-Item -Path "$releaseDir\ShowOffNVSE.dll", "$releaseDir\ShowOffNVSE.pdb" -Destination "$releaseDir\nvse\plugins"
        Copy-Item -Path "$debugDir\ShowOffNVSE.dll", "$debugDir\ShowOffNVSE.pdb" -Destination "$debugDir\nvse\plugins"
        Compress-Archive -Path "$releaseDir\nvse" -DestinationPath "artifacts\ShowOffNVSE-Release-${{ env.artifact_timestamp }}.zip"
        Compress-Archive -Path "$debugDir\nvse" -DestinationPath "artifacts\ShowOffNVSE-Debug-${{ env.artifact_timestamp }}.zip"
      shell: pwsh

    - name: Publish Zipped Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Zipped-Artifacts-${{ env.artifact_timestamp }}
        path: artifacts/
